spring:
  application:
    name: GymMeMore
  h2:
    console:
      path: /my-console
  datasource:
    url: jdbc:h2:file:./data/gymmemoredb
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      data-locations: classpath:data/*.sql
      mode: always
server:
  servlet:
    context-path: /gym-me-more
google:
  api:
    key: AIzaSyATfdizi8xbYN8yFr1IrnhTwZl1ZcxW874
